# Project Information
site_name: Horizon PowerCLI
site_url: https://euc-dev.github.io/horizon-powercli
site_author: Phil Helmling
site_description: Submodule for developer.omnissa.com
docs_dir: docs
site_dir: .site
use_directory_urls: true

# Repository
repo_url: https://github.com/euc-dev/horizon-powercli
edit_uri: edit/main/docs/

# Copyright
copyright: |
  Copyright &copy; 2005-2025 Omnissa, LLC. All rights reserved.<br/>

# Configuration
theme:
  name: material
  #custom_dir: overrides
  favicon: assets/logos/favicon-light.svg
  logo: assets/logos/favicon-dark.svg
  admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
    annotation: material/circle-medium
    annotation: material/record-circle
    annotation: material/arrow-right-circle
    annotation: material/arrow-right-circle-outline
    annotation: material/chevron-right-circle
    annotation: material/star-four-points-circle
    annotation: material/plus-circle-outline
  palette:
    scheme: omnissa
    primary: dark-shade-blue
    accent: neon
  font:
    text: Outfit
    code: Poppins
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.header
  - navigation.indexes
  - navigation.instant
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - open-in-new-tab
  - markdownextradata:
      jinja_options:
        variable_start_string: "${{"
        variable_end_string: "}}"
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: false
      exclude:
        - index.md
      fallback_to_build_date: true
      type: timeago
  - swagger-ui-tag:
        docExpansion: none
        filter: ""
        syntaxHighlightTheme: monokai
  - monorepo
  - macros

# Customization
extra:
  homepage: https://omnissa.com

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/footer.Cx6ysBfj.css
  - assets/stylesheets/neoteroi-mkdocsoad.css
  - assets/stylesheets/neoteroi-mkdocs.css

extra_javascript:
  - assets/javascripts/tablesort.min.js #https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - neoteroi.spantable
  - neoteroi.cards
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
        - material/.icons
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets:
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - index.md
  - Connect-HVServer: connect-hvserver/index.md
  - Disconnect-HVServer: disconnect-hvserver/index.md
  - Download: download/index.md
  - Omnissa.Horizon.Helper:
    - Add-HVDesktop: Omnissa.Horizon.Helper/Add-HVDesktop.md
    - Add-HVRDSServer: Omnissa.Horizon.Helper/Add-HVRDSServer.md
    - Clear-HVEventDatabase: Omnissa.Horizon.Helper/Clear-HVEventDatabase.md
    - Connect-HVEvent: Omnissa.Horizon.Helper/Connect-HVEvent.md
    - Disconnect-HVEvent: Omnissa.Horizon.Helper/Disconnect-HVEvent.md
    - Get-HVApplication: Omnissa.Horizon.Helper/Get-HVApplication.md
    - Get-HVBaseImageVM: Omnissa.Horizon.Helper/Get-HVBaseImageVM.md
    - Get-HVEntitlement: Omnissa.Horizon.Helper/Get-HVEntitlement.md
    - Get-HVEvent: Omnissa.Horizon.Helper/Get-HVEvent.md
    - Get-HVEventDatabase: Omnissa.Horizon.Helper/Get-HVEventDatabase.md
    - Get-HVFarm: Omnissa.Horizon.Helper/Get-HVFarm.md
    - Get-HVFarmSummary: Omnissa.Horizon.Helper/Get-HVFarmSummary.md
    - Get-HVGlobalEntitlement: Omnissa.Horizon.Helper/Get-HVGlobalEntitlement.md
    - Get-HVGlobalSession: Omnissa.Horizon.Helper/Get-HVGlobalSession.md
    - Get-HVGlobalSettings: Omnissa.Horizon.Helper/Get-HVGlobalSettings.md
    - Get-HVHealth: Omnissa.Horizon.Helper/Get-HVHealth.md
    - Get-HVHomeSite: Omnissa.Horizon.Helper/Get-HVHomeSite.md
    - Get-HVInternalName: Omnissa.Horizon.Helper/Get-HVInternalName.md
    - Get-HVLocalSession: Omnissa.Horizon.Helper/Get-HVLocalSession.md
    - Get-HVMachine: Omnissa.Horizon.Helper/Get-HVMachine.md
    - Get-HVMachineSummary: Omnissa.Horizon.Helper/Get-HVMachineSummary.md
    - Get-HVPodFederation: Omnissa.Horizon.Helper/Get-HVPodFederation.md
    - Get-HVPool: Omnissa.Horizon.Helper/Get-HVPool.md
    - Get-HVPoolSpec: Omnissa.Horizon.Helper/Get-HVPoolSpec.md
    - Get-HVPoolSummary: Omnissa.Horizon.Helper/Get-HVPoolSummary.md
    - Get-HVPreInstalledApplication: Omnissa.Horizon.Helper/Get-HVPreInstalledApplication.md
    - Get-HVQueryFilter: Omnissa.Horizon.Helper/Get-HVQueryFilter.md
    - Get-HVQueryResult: Omnissa.Horizon.Helper/Get-HVQueryResult.md
    - Get-HVResourceStructure: Omnissa.Horizon.Helper/Get-HVResourceStructure.md
    - Get-HVSite: Omnissa.Horizon.Helper/Get-HVSite.md
    - Get-HVlicense: Omnissa.Horizon.Helper/Get-HVlicense.md
    - Get-HVvCenterServer: Omnissa.Horizon.Helper/Get-HVvCenterServer.md
    - Get-HVvCenterServerHealth: Omnissa.Horizon.Helper/Get-HVvCenterServerHealth.md
    - New-HVEntitlement: Omnissa.Horizon.Helper/New-HVEntitlement.md
    - New-HVFarm: Omnissa.Horizon.Helper/New-HVFarm.md
    - New-HVGlobalEntitlement: Omnissa.Horizon.Helper/New-HVGlobalEntitlement.md
    - New-HVHomeSite: Omnissa.Horizon.Helper/New-HVHomeSite.md
    - New-HVManualApplication: Omnissa.Horizon.Helper/New-HVManualApplication.md
    - New-HVPodFederation: Omnissa.Horizon.Helper/New-HVPodFederation.md
    - New-HVPool: Omnissa.Horizon.Helper/New-HVPool.md
    - New-HVPreInstalledApplication: Omnissa.Horizon.Helper/New-HVPreInstalledApplication.md
    - New-HVSite: Omnissa.Horizon.Helper/New-HVSite.md
    - Register-HVPod: Omnissa.Horizon.Helper/Register-HVPod.md
    - Remove-HVApplication: Omnissa.Horizon.Helper/Remove-HVApplication.md
    - Remove-HVApplicationIcon: Omnissa.Horizon.Helper/Remove-HVApplicationIcon.md
    - Remove-HVEntitlement: Omnissa.Horizon.Helper/Remove-HVEntitlement.md
    - Remove-HVFarm: Omnissa.Horizon.Helper/Remove-HVFarm.md
    - Remove-HVGlobalEntitlement: Omnissa.Horizon.Helper/Remove-HVGlobalEntitlement.md
    - Remove-HVMachine: Omnissa.Horizon.Helper/Remove-HVMachine.md
    - Remove-HVPodFederation: Omnissa.Horizon.Helper/Remove-HVPodFederation.md
    - Remove-HVPool: Omnissa.Horizon.Helper/Remove-HVPool.md
    - Remove-HVSite: Omnissa.Horizon.Helper/Remove-HVSite.md
    - Reset-HVMachine: Omnissa.Horizon.Helper/Reset-HVMachine.md
    - Set-HVApplication: Omnissa.Horizon.Helper/Set-HVApplication.md
    - Set-HVApplicationIcon: Omnissa.Horizon.Helper/Set-HVApplicationIcon.md
    - Set-HVEventDatabase: Omnissa.Horizon.Helper/Set-HVEventDatabase.md
    - Set-HVFarm: Omnissa.Horizon.Helper/Set-HVFarm.md
    - Set-HVGlobalEntitlement: Omnissa.Horizon.Helper/Set-HVGlobalEntitlement.md
    - Set-HVGlobalSettings: Omnissa.Horizon.Helper/Set-HVGlobalSettings.md
    - Set-HVInstantCloneMaintenance: Omnissa.Horizon.Helper/Set-HVInstantCloneMaintenance.md
    - Set-HVMachine: Omnissa.Horizon.Helper/Set-HVMachine.md
    - Set-HVPodFederation: Omnissa.Horizon.Helper/Set-HVPodFederation.md
    - Set-HVPool: Omnissa.Horizon.Helper/Set-HVPool.md
    - Set-HVSite: Omnissa.Horizon.Helper/Set-HVSite.md
    - Set-HVlicense: Omnissa.Horizon.Helper/Set-HVlicense.md
    - Start-HVFarm: Omnissa.Horizon.Helper/Start-HVFarm.md
    - Start-HVPool: Omnissa.Horizon.Helper/Start-HVPool.md
    - Unregister-HVPod: Omnissa.Horizon.Helper/Unregister-HVPod.md

